/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 13
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_use = 1,
  anon_sym_SEMI = 2,
  anon_sym_COLON_COLON = 3,
  sym_identifier = 4,
  sym_unit = 5,
  anon_sym_true = 6,
  anon_sym_false = 7,
  sym_byte = 8,
  sym_char = 9,
  sym_integer = 10,
  sym_float = 11,
  sym_static_string = 12,
  anon_sym_LBRACK = 13,
  anon_sym_COMMA = 14,
  anon_sym_RBRACK = 15,
  sym_object_literal = 16,
  sym_source_file = 17,
  sym__item = 18,
  sym__expression = 19,
  sym_use_declaration = 20,
  sym_path = 21,
  sym__primitive = 22,
  sym_boolean = 23,
  sym_vector = 24,
  aux_sym_source_file_repeat1 = 25,
  aux_sym_path_repeat1 = 26,
  aux_sym_vector_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_use] = "use",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON_COLON] = "::",
  [sym_identifier] = "identifier",
  [sym_unit] = "unit",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_byte] = "byte",
  [sym_char] = "char",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_static_string] = "static_string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_object_literal] = "object_literal",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym__expression] = "_expression",
  [sym_use_declaration] = "use_declaration",
  [sym_path] = "path",
  [sym__primitive] = "_primitive",
  [sym_boolean] = "boolean",
  [sym_vector] = "vector",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_path_repeat1] = "path_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [sym_identifier] = sym_identifier,
  [sym_unit] = sym_unit,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_byte] = sym_byte,
  [sym_char] = sym_char,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_static_string] = sym_static_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_object_literal] = sym_object_literal,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym__expression] = sym__expression,
  [sym_use_declaration] = sym_use_declaration,
  [sym_path] = sym_path,
  [sym__primitive] = sym__primitive,
  [sym_boolean] = sym_boolean,
  [sym_vector] = sym_vector,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_path_repeat1] = aux_sym_path_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_byte] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_static_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_object_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym__primitive] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_path_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 2,
        '#', 7,
        '\'', 11,
        '(', 5,
        ',', 36,
        ':', 6,
        ';', 14,
        '[', 35,
        ']', 37,
        'b', 16,
        'f', 17,
        't', 22,
        'u', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 7,
        '\'', 11,
        '(', 5,
        '[', 35,
        ']', 37,
        'b', 16,
        'f', 17,
        't', 22,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(34);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(31);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(27);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '{') ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '}') ADVANCE(38);
      END_STATE();
    case 9:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_unit);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_byte);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_integer);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_static_string);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_object_literal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 9},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_unit] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_byte] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_static_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_object_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym__item] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_use_declaration] = STATE(3),
    [sym__primitive] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_vector] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_use] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_unit] = ACTIONS(9),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(9),
    [sym_char] = ACTIONS(9),
    [sym_integer] = ACTIONS(7),
    [sym_float] = ACTIONS(9),
    [sym_static_string] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_object_literal] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym__primitive] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_vector] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_use] = ACTIONS(17),
    [sym_identifier] = ACTIONS(20),
    [sym_unit] = ACTIONS(23),
    [anon_sym_true] = ACTIONS(26),
    [anon_sym_false] = ACTIONS(26),
    [sym_byte] = ACTIONS(23),
    [sym_char] = ACTIONS(23),
    [sym_integer] = ACTIONS(20),
    [sym_float] = ACTIONS(23),
    [sym_static_string] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(29),
    [sym_object_literal] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__item] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_use_declaration] = STATE(2),
    [sym__primitive] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_vector] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(32),
    [anon_sym_use] = ACTIONS(5),
    [sym_identifier] = ACTIONS(34),
    [sym_unit] = ACTIONS(36),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(36),
    [sym_char] = ACTIONS(36),
    [sym_integer] = ACTIONS(34),
    [sym_float] = ACTIONS(36),
    [sym_static_string] = ACTIONS(36),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_object_literal] = ACTIONS(36),
  },
  [STATE(4)] = {
    [sym__expression] = STATE(15),
    [sym__primitive] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_vector] = STATE(15),
    [sym_identifier] = ACTIONS(38),
    [sym_unit] = ACTIONS(40),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(40),
    [sym_char] = ACTIONS(40),
    [sym_integer] = ACTIONS(38),
    [sym_float] = ACTIONS(40),
    [sym_static_string] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(42),
    [sym_object_literal] = ACTIONS(40),
  },
  [STATE(5)] = {
    [sym__expression] = STATE(21),
    [sym__primitive] = STATE(21),
    [sym_boolean] = STATE(21),
    [sym_vector] = STATE(21),
    [sym_identifier] = ACTIONS(44),
    [sym_unit] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(46),
    [sym_char] = ACTIONS(46),
    [sym_integer] = ACTIONS(44),
    [sym_float] = ACTIONS(46),
    [sym_static_string] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(48),
    [sym_object_literal] = ACTIONS(46),
  },
  [STATE(6)] = {
    [sym__expression] = STATE(21),
    [sym__primitive] = STATE(21),
    [sym_boolean] = STATE(21),
    [sym_vector] = STATE(21),
    [sym_identifier] = ACTIONS(44),
    [sym_unit] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(46),
    [sym_char] = ACTIONS(46),
    [sym_integer] = ACTIONS(44),
    [sym_float] = ACTIONS(46),
    [sym_static_string] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_RBRACK] = ACTIONS(50),
    [sym_object_literal] = ACTIONS(46),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(52),
    [anon_sym_use] = ACTIONS(54),
    [sym_identifier] = ACTIONS(54),
    [sym_unit] = ACTIONS(52),
    [anon_sym_true] = ACTIONS(54),
    [anon_sym_false] = ACTIONS(54),
    [sym_byte] = ACTIONS(52),
    [sym_char] = ACTIONS(52),
    [sym_integer] = ACTIONS(54),
    [sym_float] = ACTIONS(52),
    [sym_static_string] = ACTIONS(52),
    [anon_sym_LBRACK] = ACTIONS(52),
    [anon_sym_COMMA] = ACTIONS(52),
    [anon_sym_RBRACK] = ACTIONS(52),
    [sym_object_literal] = ACTIONS(52),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [anon_sym_use] = ACTIONS(58),
    [sym_identifier] = ACTIONS(58),
    [sym_unit] = ACTIONS(56),
    [anon_sym_true] = ACTIONS(58),
    [anon_sym_false] = ACTIONS(58),
    [sym_byte] = ACTIONS(56),
    [sym_char] = ACTIONS(56),
    [sym_integer] = ACTIONS(58),
    [sym_float] = ACTIONS(56),
    [sym_static_string] = ACTIONS(56),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_COMMA] = ACTIONS(56),
    [anon_sym_RBRACK] = ACTIONS(56),
    [sym_object_literal] = ACTIONS(56),
  },
  [STATE(9)] = {
    [sym__expression] = STATE(21),
    [sym__primitive] = STATE(21),
    [sym_boolean] = STATE(21),
    [sym_vector] = STATE(21),
    [sym_identifier] = ACTIONS(44),
    [sym_unit] = ACTIONS(46),
    [anon_sym_true] = ACTIONS(11),
    [anon_sym_false] = ACTIONS(11),
    [sym_byte] = ACTIONS(46),
    [sym_char] = ACTIONS(46),
    [sym_integer] = ACTIONS(44),
    [sym_float] = ACTIONS(46),
    [sym_static_string] = ACTIONS(46),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_object_literal] = ACTIONS(46),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [anon_sym_use] = ACTIONS(62),
    [sym_identifier] = ACTIONS(62),
    [sym_unit] = ACTIONS(60),
    [anon_sym_true] = ACTIONS(62),
    [anon_sym_false] = ACTIONS(62),
    [sym_byte] = ACTIONS(60),
    [sym_char] = ACTIONS(60),
    [sym_integer] = ACTIONS(62),
    [sym_float] = ACTIONS(60),
    [sym_static_string] = ACTIONS(60),
    [anon_sym_LBRACK] = ACTIONS(60),
    [anon_sym_COMMA] = ACTIONS(60),
    [anon_sym_RBRACK] = ACTIONS(60),
    [sym_object_literal] = ACTIONS(60),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [anon_sym_use] = ACTIONS(66),
    [sym_identifier] = ACTIONS(66),
    [sym_unit] = ACTIONS(64),
    [anon_sym_true] = ACTIONS(66),
    [anon_sym_false] = ACTIONS(66),
    [sym_byte] = ACTIONS(64),
    [sym_char] = ACTIONS(64),
    [sym_integer] = ACTIONS(66),
    [sym_float] = ACTIONS(64),
    [sym_static_string] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_RBRACK] = ACTIONS(64),
    [sym_object_literal] = ACTIONS(64),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [anon_sym_use] = ACTIONS(70),
    [sym_identifier] = ACTIONS(70),
    [sym_unit] = ACTIONS(68),
    [anon_sym_true] = ACTIONS(70),
    [anon_sym_false] = ACTIONS(70),
    [sym_byte] = ACTIONS(68),
    [sym_char] = ACTIONS(68),
    [sym_integer] = ACTIONS(70),
    [sym_float] = ACTIONS(68),
    [sym_static_string] = ACTIONS(68),
    [anon_sym_LBRACK] = ACTIONS(68),
    [anon_sym_COMMA] = ACTIONS(68),
    [anon_sym_RBRACK] = ACTIONS(68),
    [sym_object_literal] = ACTIONS(68),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(74), 5,
      anon_sym_use,
      sym_identifier,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
    ACTIONS(72), 8,
      ts_builtin_sym_end,
      sym_unit,
      sym_byte,
      sym_char,
      sym_float,
      sym_static_string,
      anon_sym_LBRACK,
      sym_object_literal,
  [18] = 3,
    ACTIONS(76), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    STATE(19), 1,
      aux_sym_path_repeat1,
  [28] = 3,
    ACTIONS(80), 1,
      anon_sym_COMMA,
    ACTIONS(82), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      aux_sym_vector_repeat1,
  [38] = 3,
    ACTIONS(48), 1,
      anon_sym_RBRACK,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_vector_repeat1,
  [48] = 3,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      aux_sym_vector_repeat1,
  [58] = 3,
    ACTIONS(91), 1,
      anon_sym_SEMI,
    ACTIONS(93), 1,
      anon_sym_COLON_COLON,
    STATE(18), 1,
      aux_sym_path_repeat1,
  [68] = 3,
    ACTIONS(78), 1,
      anon_sym_COLON_COLON,
    ACTIONS(96), 1,
      anon_sym_SEMI,
    STATE(18), 1,
      aux_sym_path_repeat1,
  [78] = 2,
    ACTIONS(98), 1,
      sym_identifier,
    STATE(23), 1,
      sym_path,
  [85] = 1,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [90] = 1,
    ACTIONS(91), 2,
      anon_sym_SEMI,
      anon_sym_COLON_COLON,
  [95] = 1,
    ACTIONS(100), 1,
      anon_sym_SEMI,
  [99] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
  [103] = 1,
    ACTIONS(104), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(13)] = 0,
  [SMALL_STATE(14)] = 18,
  [SMALL_STATE(15)] = 28,
  [SMALL_STATE(16)] = 38,
  [SMALL_STATE(17)] = 48,
  [SMALL_STATE(18)] = 58,
  [SMALL_STATE(19)] = 68,
  [SMALL_STATE(20)] = 78,
  [SMALL_STATE(21)] = 85,
  [SMALL_STATE(22)] = 90,
  [SMALL_STATE(23)] = 95,
  [SMALL_STATE(24)] = 99,
  [SMALL_STATE(25)] = 103,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 5, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_declaration, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_path_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [102] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rune(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rune",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
